char a; char b; char c;
int  d; int  e; int  f;
long g; long h; long i;


int main() {
  b= 5; c= 7; a= b + c++; print_int(a);
  e= 5; f= 7; d= e + f++; print_int(d);
  h= 5; i= 7; g= h + i++; print_int(g);
  a= b-- + c; print_int(a);
  d= e-- + f; print_int(d);
  g= h-- + i; print_int(g);
  a= ++b + c; print_int(a);
  d= ++e + f; print_int(d);
  g= ++h + i; print_int(g);
  a= b * --c; print_int(a);
  d= e * --f; print_int(d);
  g= h * --i; print_int(g);
  return(0);
}
