#!/bin/sh

if [ ! -f ../parser ]
  then echo "Need to build parser first"; exit 1;
fi

for i in input*
  do if [ ! -f "out.$i" ]
      then echo "Can't run test on $i, no input file"
      else
        echo -n $i
        ../parser $i
        cc -o out out.s
        ./out > trial.$i
        cmp -s "out.$i" "trial.$i"

        if [ "$?" -eq "1" ]
        then
          echo ": Failed"
          diff -c "out.$i" "trial.$i"
          echo
        else
          echo ": Ok"
        fi
        rm -rf out out.s "trial.$i"
      fi
  done
