#!/bin/bash

PARSER=../parser
PARSER_NAME=parser

if [[ $1 = 0  ||  $1 = 2  ||  $1 = 2 ]]; then
  PARSER=../parser$1
  PARSER_NAME=parser$1
fi

echo "Use $PARSER"

if [ ! -f $PARSER ];
  then (cd ..; make clean && make $PARSER_NAME);
fi

for i in input*
  do if [ ! -f "assert/out.$i" -a ! -f "error/error.$i" ];
     then
       echo "Can't run test on $i, no output file!"

      else if [ -f "assert/out.$i" ];
      then
        echo -n "test $i..."
        $PARSER -o out $i
        ./out > assert/trial.$i
        cmp -s "assert/out.$i" "assert/trial.$i"
        if [ "$?" -eq "1" ];
        then
          echo ": Failed"
          diff -c "assert/out.$i" "assert/trial.$i"
          echo
        else
          echo ": Ok"
        fi

        else if [ -f "error/error.$i" ];
        then
          echo -n "gen $i error file..."
          $PARSER $i 2> "assert/trial.$i"
          cmp -s "error/error.$i" "assert/trial.$i"
          if [ "$?" -eq "1" ];
          then
            echo ": Failed"
            diff -c "error/error.$i" "assert/trial.$i"
            echo
          else
            echo ": Ok"
          fi
        fi

      fi
     fi
     rm -rf out out.s "assert/trial.$i" *.s *.o
  done
