#!/bin/sh

if [ ! -f ../parser ]
  then (cd ..; make clean && make);
fi

for i in input*
  do if [ ! -f "assert/out.$i" -a ! -f "error/error.$i" ];
     then
       echo "Can't run test on $i, no output file!"

      else if [ -f "assert/out.$i" ];
      then
        echo -n "test $i..."
        ../parser -o out $i
        ./out > assert/trial.$i
        cmp -s "assert/out.$i" "assert/trial.$i"
        if [ "$?" -eq "1" ];
        then
          echo ": Failed"
          diff -c "assert/out.$i" "assert/trial.$i"
          echo
        else
          echo ": Ok"
        fi

        else if [ -f "error/error.$i" ];
        then
          echo -n "gen $i error file..."
          ../parser $i 2> "assert/trial.$i"
          cmp -s "error/error.$i" "assert/trial.$i"
          if [ "$?" -eq "1" ];
          then
            echo ": Failed"
            diff -c "error/error.$i" "assert/trial.$i"
            echo
          else
            echo ": Ok"
          fi
        fi

      fi
     fi
     rm -rf out out.s "assert/trial.$i" *.s *.o
  done
